# -*- coding: utf-8 -*-
"""lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11yFvmJIUcjLAcM_nCW9KFw-8iIYxOxVd
"""

file1=open('/content/sample_data.txt','r')
text=file1.read()
print(text)

file2=open('/content/sample_data.txt')
text=file2.readlines()
print(text)

file_path='/content/data.tsv'
def count_line(file_path):
  with open(file_path, 'r',errors='ignore') as file:
    lines = file.readlines()
    return len(lines)

line_count = count_line(file_path)
print(f'The number of lines in the file is: {line_count}')

file_path='/content/data.tsv'
def count_fields(file_path):
  with open(file_path,'r') as file:
    first_line=file.readline().strip()
    fields=first_line.split()
    return len(fields)

field_count=count_fields(file_path)
print(f'The number of fields in the first line is:{field_count}')

import pandas as pd

try:
    df = pd.read_csv('/content/data.tsv', delimiter='\t', encoding='utf-8')
except UnicodeDecodeError:
    df = pd.read_csv('/content/data.tsv', delimiter='\t', encoding='ISO-8859-1')

rows, columns = df.shape

print(f"Number of rows: {rows}")
print(f"Number of columns: {columns}")